### PR TITLE
Add extract_zim build

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by Kubuxu** [comment]
@dignifiedquire I am not sure if it is the cleanest way to do it but it works.

**Comment by dignifiedquire** [comment]
you require cargo + rust anyway so you can do just `cargo install github.com/dignifiedquire/extract-zim`

**Comment by Kubuxu** [comment]
Can I select commit with it?

**Comment by dignifiedquire** [comment]
yes try cargo install --help to see the options how to apecify

**Comment by Kubuxu** [comment]
Getting:
```
cargo install --root . --rev a283151105ab4c1905d7f5cb56fb8eb2a854ad67 github.com/dignifiedquire/extract-zim
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `github.com/dignifiedquire/extract-zim` in `registry https://github.com/rust-lang/crates.io-index`
make: *** [Makefile:4: extract_zim] Error 101
```
I will just use what I did here.

**Comment by dignifiedquire** [comment]
@Kubuxu this works

```
> cargo install --rev a283151105ab4c1905d7f5cb56fb8eb2a854ad67 --git https://github.com/dignifiedquire/zim
```

**Comment by Kubuxu** [comment]
Updated it.

**Pull request merged**
