### PR TITLE
feat: wikipedia_en_all_maxi_2021-02

### LINKED ISSUE #61: Update en.wikipedia-on-ipfs.org
- [x] set up domain name `en.wikipedia-on-ipfs.org` (https://github.com/ipfs/infra/issues/491)
- [x] [create new (test) snapshot](https://github.com/ipfs/distributed-wikipedia-mirror#how-to-add-new-wikipedia-snapshots-to-ipfs)
- [x] ensure canonical link is correct
  - this is blocked on upstream snapshots or updating our scripts: https://github.com/ipfs/distributed-wikipedia-mirror/issues/48#issuecomment-527230858  + https://github.com/ipfs/distributed-wikipedia-mirror/issues/65
- [x] ensure footer is updated (https://github.com/ipfs/distributed-wikipedia-mirror/issues/64)
- [ ] does search work / can work?
- [x] recreate snapshot if needed
- [ ] pin
  - [ ] set up collaborative pinning cluster (https://github.com/ipfs/distributed-wikipedia-mirror/issues/68)
- [ ] update DNSLink at en.wikipedia-on-ipfs.org (https://github.com/ipfs/infra/issues/491)

This could be done manually or as a part of #58

### PR DESCRIPTION
**Pull request by lidel**
This PR updates English  version to snapshot from 2021-02 and closes #61

Generated from `wikipedia_en_all_maxi_2021-02.zim`, includes fix from  #90: 

- https://dweb.link/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze

If it loads slow from gateway, try to connect to the origin node via
`ipfs swarm connect /p2p/12D3KooWFRcqpEhdCfAY6HYcrJaQjDBbPNp2ycxDY54LZNx6UgLM`

Thanks!

## TODO

- [x] get OK from native  speaker
  - Before we pin this,  @kelson42  @mburns @autonome mind checking if the above snapshot looks good and give final OK?
- [x] pin
  - (after I have pin confirmation, I can remove `en` from my SSD and bulid `ru` and `ar` )
- [x] update DNSLink
- [x] add to https://collab.ipfscluster.io/

### CODE REVIEW

**Comment by kelson42** [comment]
@lidel Looks good to me

**Comment by kelson42** [comment]
@lidel Looks good to me

**Comment by lidel** [comment]
`*.dev` version at https://en.dev.wikipedia-on-ipfs.org is ready for testing, pinning in progress.

**Comment by lidel** [comment]
DEV version at  https://en.dev.wikipedia-on-ipfs.org is pinned and ready for final testing. 
It was very time-consuming endeavor, so unless there are critical blockers, we plan to ship https://github.com/ipfs/distributed-wikipedia-mirror/pull/92  to production next week.

**Comment by kelson42** [comment]
Looks good to me, even if the http gateway is still pretty slow

**Pull request merged**
