### PR TITLE
Add Myanmar Wikipedia

### PR DESCRIPTION
**Pull request by lidel**
`my` is small enough to generate it before #61, given the current context: 
- https://netblocks.org/reports/internet-disrupted-in-myanmar-amid-apparent-military-uprising-JBZrmlB6
- Wikipedia blocked: https://twitter.com/netblocks/status/1362814793502097409

## Preview 

- https://bafybeib66xujztkiq7lqbupfz6arzhlncwagva35dx54nj7ipyoqpyozhy.ipfs.dweb.link/wiki/

## Remaining work

This is WIP:

- [x] generate snapshot for 2021-02
- [x] fix main page
- [x] waiting for QA from native speaker
- [x] set DNSLink
- [ ] add to collab cluster

### CODE REVIEW

**Comment by arky** [comment]
Waiting for response from native speakers. Meanwhile I think there is a font warning on the main page. 

> https://bafybeib66xujztkiq7lqbupfz6arzhlncwagva35dx54nj7ipyoqpyozhy.ipfs.dweb.link/wiki/%E1%80%9D%E1%80%AE%E1%80%80%E1%80%AE%E1%80%95%E1%80%AE%E1%80%B8%E1%80%92%E1%80%AE%E1%80%B8%E1%80%9A%E1%80%AC%E1%80%B8:Font


`ipfs resolve -r /ipfs/bafybeib66xujztkiq7lqbupfz6arzhlncwagva35dx54nj7ipyoqpyozhy/wiki/%E1%80%9D%E1%80%AE%E1%80%80%E1%80%AE%E1%80%95%E1%80%AE%E1%80%B8%E1%80%92%E1%80%AE%E1%80%B8%E1%80%9A%E1%80%AC%E1%80%B8:Font: no link named "ဝီကီပီးဒီးယား:Font" under bafybeifhhojjjrfody2knggqnnns2cw7q77uxg5pgeiedz6ci5el6cgbvi`

**Comment by arky** [comment]
Here is the feedback I received from Myanmar:

>  I've checked the link.  I can directly access to it using Chrome browser.  And the links are also working well.

**Comment by kelson42** [comment]
Have already updated our portal https://ipfs.kiwix.org/

**Comment by arky** [comment]
@kelson42  Am getting a 404 error 

> $ curl https://my.wikipedia-on-ipfs.org/
> 404 page not found
>

**Comment by lidel** [comment]
Thank you all!  I'm waiting for DNSLink update before merging this. 

@hsanjuan what is the process for adding this to https://collab.ipfscluster.io?

**Comment by arky** [comment]
@lidel  Result of quick QA from a native speaker: the Myanmar text rendering looks good and also the main page content is acceptable.

**Comment by lidel** [comment]
DNSLink is live, pinning in progress, merging.

**Comment by arky** [comment]
Thanks @lidel Please give me ping so I can propagate this when Myanmar wakes up from blackout tomorrow morning.

**Comment by lidel** [comment]
@arky below links may be useful:

- HTTP address: https://my.wikipedia-on-ipfs.org
- P2P address (requires IPFS node enabled in  [Brave](https://brave.com/ipfs-support/)):  `ipns://my.wikipedia-on-ipfs.org`
    - immutable copy can be always reached via  (even if DNS is blocked): `ipfs://bafybeib66xujztkiq7lqbupfz6arzhlncwagva35dx54nj7ipyoqpyozhy`
- :point_right:  In case DNS is censored and using Brave is not an option,  [public gateways](https://ipfs.github.io/public-gateway-checker/) can be used as HTTP mirrors:  
    - https://dweb.link/ipns/my.wikipedia-on-ipfs.org (PL gateway)
    - https://my-wikipedia--on--ipfs-org.ipns.cf-ipfs.com (Cloudflare)
      -  (some vendors need to update their go-ipfs to 0.8.0,  then we can use https://cf-ipfs.com/ipns/my.wikipedia-on-ipfs.org without  TLS error)

**Comment by lidel** [comment]
Shipped. Thank you all! :heart:

**Comment by lidel** [comment]
@arky As you can read in the footer of every page, IPFS mirror it includes both an unpacked version (that can be loaded in browser)  and the original ZIM archive that can be downloaded and read with one of [many offline readers](https://www.kiwix.org/en/kiwix-reader), maximizing the utility of this project.

**Pull request merged**
